apiVersion: v1
kind: Service
metadata:
  name: react-snake-service
spec:
  ipFamilies:
  - IPv6
  selector:
    app: react-snake
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
