apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
spec:
  ipFamilies:
  - IPv6
  selector:
    app: portfolio
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
